spring:
  jpa:
    properties:
      hibernate:
        default_schema: public

  docker:
    compose:
      file: src/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liGiUoHUYSebPGZz
            client-secret: 37f4b362b9e07ba50ff79f3cefe24265a979260e

server:
  port: 8443
  ssl:
    key-store: keystore.p12
    key-store-password: aicha2580
    key-store-type: PKCS12
    key-alias: myapp

keycloak:
  realm: aicha-test
  auth-server-url: http://localhost:8080/auth
  resource: aicha-rest-api
  credentials:
    secret: 4NMQdJeC20rQKGM9jow4IV39NaFt1ARB
  principal-attribute: aicha
  public-client: false
  bearer-only: true
